// Prevents an additional console window on Windows in release builds, DO NOT REMOVE!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Import each Tauri command function from the library crate.
// The #[macro_export]'d __cmd__ helper macros generated by #[tauri::command]
// in lib.rs travel with the crate and are accessible to generate_handler! here.
use cs2_demo_manager_lib::{
    check_cs2_path, delete_demo_file, detect_steam_path, download_demo, get_file_info,
    import_demo, launch_cs2, list_demos, open_folder, rename_demo_file,
};

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            list_demos,
            import_demo,
            delete_demo_file,
            rename_demo_file,
            open_folder,
            launch_cs2,
            check_cs2_path,
            detect_steam_path,
            get_file_info,
            download_demo,
        ])
        .run(tauri::generate_context!())
        .expect("Fehler beim Starten der Anwendung");
}
